[package]
name = "huniq"
version = "2.3.0"
authors = ["Karolin Varner <karo@cupdev.net>"]
edition = "2018"
license = "BSD-3-Clause"
description = "Filter out duplicates on the command line. Replacement for `sort | uniq` optimized for speed (10x faster)."
readme = "readme.md"
repository = "https://github.com/koraa/huniq"
categories = ["command-line-utilities"]
keywords = ["cli", "uniq"]

[dependencies]
clap = "2.33.3"
anyhow = "1.0.32"
sysconf = "0.3.4"
memchr = "2.3.3"
ahash = "0.4.4"

[dev-dependencies]
assert_cmd = "1.0.1"
